#!/usr/bin/env bash
set -euo pipefail
root=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
port="$root/amrex_port"
required=("$port/CMakeLists.txt" "$port/CMakePresets.json" "$port/amrex_version.lock" "$port/inputs/p1_smoke.in" "$port/inputs/p1_multibox.in" "$port/inputs/p1_contract.in" "$port/inputs/p2_contract.in" "$port/inputs/p2_boundary_face.in" "$port/inputs/p3_cartesian_boundary.in" "$port/inputs/p3_legacy_supported.in" "$port/inputs/p3_legacy_rejected.in" "$port/inputs/p4_periodic_projection.in" "$port/inputs/p4_closed_neumann_projection.in" "$port/inputs/p4_inflow_outflow_projection.in" "$port/src/CartesianBoundaryConfig.H" "$port/src/CartesianBoundaryConfig.cpp" "$port/src/VwisAmrExSolver.H" "$port/src/VwisAmrExSolver.cpp" "$port/src/VwisAmrExBoundary.cpp" "$port/src/VwisAmrExProjection.cpp" "$port/src/VwisAmrExContracts.cpp")
for file in "${required[@]}"; do test -f "$file"; done
rg -q 'find_package\(AMReX CONFIG QUIET\)' "$port/CMakeLists.txt"
rg -q 'AMReXConfig.cmake was not found' "$port/CMakeLists.txt"
rg -q 'FieldLocation' "$port/src/VwisAmrExSolver.H"
rg -q 'component_names' "$port/src/VwisAmrExSolver.H"
rg -q 'm_cell_volume' "$port/src/VwisAmrExSolver.H"
rg -q 'm_face_area' "$port/src/VwisAmrExSolver.H"
rg -q 'm_ucont_older' "$port/src/VwisAmrExSolver.H"
rg -q 'amrex::BCRec' "$port/src/VwisAmrExSolver.H"
rg -q 'AMREX_GPU_DEVICE' "$port/src/VwisAmrExSolver.cpp" "$port/src/VwisAmrExBoundary.cpp" "$port/src/VwisAmrExProjection.cpp" "$port/src/VwisAmrExContracts.cpp"
rg -q 'payload_written' "$port/src/VwisAmrExContracts.cpp"
rg -q 'run_runtime_contract_checks' "$port/src/VwisAmrExContracts.cpp"
rg -q 'sync_ucat_from_ucont' "$port/src/VwisAmrExSolver.cpp"
rg -q 'sync_ucont_from_ucat' "$port/src/VwisAmrExSolver.cpp"
rg -q 'OverrideSync' "$port/src/VwisAmrExSolver.cpp"
rg -q 'OwnerMask' "$port/src/VwisAmrExContracts.cpp"
rg -q 'sum_unique' "$port/src/VwisAmrExBoundary.cpp" "$port/src/VwisAmrExContracts.cpp"
rg -q 'normal velocity times face area' "$port/src/VwisAmrExSolver.cpp"
rg -q 'derived divergence' "$port/src/VwisAmrExContracts.cpp"
rg -q 'constant Ucat/Ucont volume-flux contract failed' "$port/src/VwisAmrExContracts.cpp"
rg -q 'base runtime contract: PASS' "$port/src/VwisAmrExContracts.cpp"
rg -q 'P2-003/004/005: PASS' "$port/src/VwisAmrExContracts.cpp"
rg -q 'enum class CartesianBC' "$port/src/CartesianBoundaryConfig.H"
rg -q 'fill_physical_ghost_cells' "$port/src/VwisAmrExBoundary.cpp"
rg -q 'stale ghost read' "$port/src/VwisAmrExSolver.cpp"
rg -q 'ReduceRealSum' "$port/src/VwisAmrExBoundary.cpp" "$port/src/VwisAmrExContracts.cpp"
rg -q 'ReduceRealMax' "$port/src/VwisAmrExContracts.cpp"
rg -q 'P3-001/002/003/004: PASS' "$port/src/VwisAmrExContracts.cpp"
rg -q 'unsupported legacy BC integer' "$port/src/CartesianBoundaryConfig.cpp"
rg -q 'AMReX_MLPoisson.H' "$port/src/VwisAmrExProjection.cpp"
rg -q 'net face flux divided by Cartesian cell volume' "$port/src/VwisAmrExProjection.cpp"
rg -q 'm_face_area\[dir\]' "$port/src/VwisAmrExProjection.cpp"
rg -q 'no automatic mean subtraction is permitted' "$port/src/VwisAmrExProjection.cpp"
rg -q 'LinOpBCType::Dirichlet' "$port/src/VwisAmrExProjection.cpp"
rg -q 'LinOpBCType::Neumann' "$port/src/VwisAmrExProjection.cpp"
rg -Fq 'sync_ucat_from_ucont_impl(false)' "$port/src/VwisAmrExProjection.cpp"
rg -q 'P4 Cartesian projection contract: PASS' "$port/src/VwisAmrExProjection.cpp"
echo 'static P0-P4 AMReX contract check: PASS'
