"""Build self-contained notebooks from concise lesson summaries and full code.

This helper uses only Python's standard library so the notebooks can be rebuilt
before NumPy, PyTorch, or nbformat are installed.
"""

from __future__ import annotations

import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parent

SECTION6_SUMMARY = r"""
# 第六节：守恒量约束 PINN 求解粘性 Burgers 方程

> 本 Notebook 已将长讲义归纳为“问题、方法、实验、结论”四条主线，并包含完整可运行代码。

## 学习目标

1. 从线性平流迁移到非线性 Burgers 方程；
2. 理解质量守恒约束如何加入 PINN；
3. 比较 Baseline PINN 与 Conservation-PINN；
4. 检查训练区间与长时间外推区间的误差和质量漂移。

## Apple Silicon 运行说明

- 第六节优先使用 MacBook 的 `mps`，不可用时自动回退到 CUDA 或 CPU；
- MPS 使用 `float32`，适合 PINN 训练；
- 如果当前 PyTorch 的 MPS 高阶自动微分报错，可设置 `cfg.device = "cpu"`；
- 首次运行保留最后一个单元中的 `RUN_QUICK = True`。

# 1. 数学问题

粘性 Burgers 方程为：

$$u_t + u u_x = \nu u_{xx}, \qquad x\in[0,1],\ t\in[0,2]$$

也可写成守恒律形式：

$$u_t+\left(\frac{u^2}{2}\right)_x=\nu u_{xx}$$

初值与周期边界为：

$$u(x,0)=1+0.5\sin(2\pi x)$$

$$u(0,t)=u(1,t),\qquad u_x(0,t)=u_x(1,t)$$

在周期边界下，总质量保持不变：

$$M(t)=\int_0^1u(x,t)\,dx=M(0)=1$$

# 2. PINN 与守恒约束

网络预测记为 $u_\theta(x,t)$，PDE 残差为：

$$f_\theta=u_t+u_\theta u_x-\nu u_{xx}$$

基础损失为：

$$\mathcal L_{\mathrm{base}}
=\lambda_{ic}\mathcal L_{ic}
+\lambda_{bc}\mathcal L_{bc}
+\lambda_f\mathcal L_f$$

守恒量损失为：

$$\mathcal L_{\mathrm{cons}}
=\frac{1}{N_t}\sum_{n=1}^{N_t}
\left|
\frac{1}{N_x}\sum_{k=1}^{N_x}u_\theta(x_k,t_n)-1
\right|^2$$

Conservation-PINN 的总损失为：

$$\mathcal L
=\mathcal L_{\mathrm{base}}
+\lambda_{\mathrm{cons}}\mathcal L_{\mathrm{cons}}$$

# 3. 公平对比实验

| 项目 | Baseline PINN | Conservation-PINN |
|---|---:|---:|
| 网络结构 | 相同 | 相同 |
| IC / BC / PDE 点 | 相同 | 相同 |
| 优化器和随机种子 | 相同 | 相同 |
| 守恒权重 | $0$ | $\lambda_{\mathrm{cons}}>0$ |

训练区间为 $t\in[0,1]$，评估延伸到 $t\in[0,2]$。重点比较：

$$E_{L2}=\frac{\|u_\theta-u_{\mathrm{ref}}\|_2}{\|u_{\mathrm{ref}}\|_2}$$

$$E_{\mathrm{cons}}(t)=|M_\theta(t)-1|$$

守恒误差更小不代表所有点的误差一定更小，因此必须同时看解场、时间切片、相对误差和质量漂移。

# 4. 实验流程

1. 用周期伪谱法生成参考解；
2. 训练 Baseline PINN；
3. 训练 Conservation-PINN；
4. 输出训练曲线、解场误差、质量漂移、时间切片和 CSV 指标；
5. 正式实验可比较 $\lambda_{\mathrm{cons}}=0.1,1,10$。
"""


SECTION7_SUMMARY = r"""
# 第七节：双摆 Hamilton 系统与正则变换

> 本 Notebook 聚焦一个核心问题：同一个 Hamilton 系统换到另一组正则坐标后，物理轨迹是否保持一致？

## 学习目标

1. 理解 Hamilton 状态变量 $z=(q,p)$；
2. 用自动微分构造 Hamilton 正则方程；
3. 构造并验证一个正则变换；
4. 比较原坐标与新坐标中的数值轨迹；
5. 用能量漂移和坐标一致性评价结果。

## Apple Silicon 运行说明

- 本节故意使用 **CPU + float64**；
- Apple Silicon 的 MPS 不支持 `float64`；
- Hamiltonian 漂移本身通常很小，双精度比 GPU 加速更重要。

# 1. 双摆 Hamiltonian

状态变量为：

$$z=(q_1,q_2,p_1,p_2)^T$$

其中 $q_1,q_2$ 是两根杆相对竖直向下方向的绝对角度，$p_1,p_2$ 是共轭动量。令：

$$\Delta=q_1-q_2$$

Hamiltonian 为：

$$
H(q,p)=
\frac{
m_2l_2^2p_1^2+(m_1+m_2)l_1^2p_2^2
-2m_2l_1l_2\cos\Delta\,p_1p_2
}{
2m_2l_1^2l_2^2(m_1+m_2\sin^2\Delta)
}
-(m_1+m_2)gl_1\cos q_1-m_2gl_2\cos q_2
$$

无阻尼、无外力且 $H$ 不显含时间，因此理论上：

$$\frac{dH}{dt}=0$$

# 2. Hamilton 正则方程

正则方程写为：

$$\dot q_i=\frac{\partial H}{\partial p_i},
\qquad
\dot p_i=-\frac{\partial H}{\partial q_i}$$

向量形式为：

$$\dot z=J\nabla_zH,\qquad
J=\begin{bmatrix}0&I\\-I&0\end{bmatrix}$$

代码使用 PyTorch 自动微分计算 $\nabla_zH$，避免手工展开复杂导数。

# 3. 正则变换

选择第二类生成函数：

$$F_2(q,P)=q_1P_1+(q_2-q_1)P_2$$

得到新变量：

$$Q_1=q_1,\qquad Q_2=q_2-q_1$$

$$P_1=p_1+p_2,\qquad P_2=p_2$$

逆变换为：

$$q_1=Q_1,\qquad q_2=Q_1+Q_2$$

$$p_1=P_1-P_2,\qquad p_2=P_2$$

新 Hamiltonian 为：

$$K(Q,P)=H(Q_1,Q_1+Q_2,P_1-P_2,P_2)$$

正则性通过矩阵条件检查：

$$A^TJA=J$$

# 4. 对比实验与正确结论

两组坐标描述的是同一个物理系统。将新坐标结果映射回原坐标后，应满足：

$$E_z(t)=\|z_{\mathrm{direct}}(t)-z_{\mathrm{mapped}}(t)\|_2\approx0$$

能量漂移定义为：

$$E_H(t)=|H(t)-H(0)|$$

本实验为公平比较，在两组坐标中都使用 RK4。RK4 不是辛积分器，因此不会严格保持 Hamiltonian；减小时间步后，状态误差和能量漂移应下降。

# 5. 实验流程

1. 定义原始 Hamiltonian；
2. 用自动微分计算 Hamilton 方程右端项；
3. 在原始正则变量中积分；
4. 在正则变换后的变量中积分并映射回来；
5. 比较角度、末端轨迹、状态误差与 Hamiltonian 漂移。
"""

CODE_TITLE_TRANSLATIONS = {
    "Imports and configuration": "导入库、参数与 Apple Silicon 设备选择",
    "A periodic pseudo-spectral reference solver": "周期伪谱参考解",
    "PINN model and automatic differentiation": "PINN 网络与自动微分",
    "Training": "统一训练函数",
    "Evaluation helpers": "评估指标",
    "Figures required by the lesson": "结果可视化",
    "Complete experiment": "完整对比实验",
    "Imports and physical parameters": "导入库与双摆物理参数",
    "Hamiltonian in the original canonical variables z = (q1, q2, p1, p2)": "原始正则变量中的 Hamiltonian 与自动微分",
    "A canonical transformation generated by F2(q,P)": "由生成函数构造正则变换",
    "The same RK4 integrator is used for a fair coordinate comparison": "用于公平坐标对比的 RK4",
    "Evaluation and plotting": "误差评价与可视化",
    "Complete comparison experiment": "完整坐标对比实验",
}


def lines(text: str) -> list[str]:
    return text.splitlines(keepends=True)


def markdown_sections(text: str) -> list[str]:
    """Split lesson Markdown at level-one headings outside fenced code blocks."""
    sections: list[list[str]] = []
    current: list[str] = []
    in_fence = False
    for line in lines(text):
        if line.lstrip().startswith("```"):
            in_fence = not in_fence
        if line.startswith("# ") and current and not in_fence:
            sections.append(current)
            current = []
        current.append(line)
    if current:
        sections.append(current)
    return ["".join(section).strip() + "\n" for section in sections]


def code_sections(text: str) -> list[tuple[str, str]]:
    """Split a percent-format Python script into named notebook code cells."""
    matches = list(re.finditer(r"^# %%\s*(.*)$", text, flags=re.MULTILINE))
    sections: list[tuple[str, str]] = []
    for index, match in enumerate(matches):
        start = match.end() + 1
        end = matches[index + 1].start() if index + 1 < len(matches) else len(text)
        source = text[start:end].strip()
        if "def parse_args()" in source:
            source = source.split("def parse_args()", 1)[0].rstrip()
        source = source.replace(
            'Path(__file__).resolve().parent / config.output_dir',
            'Path.cwd() / config.output_dir',
        )
        source = source.replace(
            'Path(__file__).resolve().parent / "results" / output_name',
            'Path.cwd() / "results" / output_name',
        )
        sections.append((match.group(1).strip(), source + "\n"))
    return sections


def markdown_cell(source: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": lines(source)}


def code_cell(source: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": lines(source),
    }


def build_notebook(
    summary_markdown: str,
    script_name: str,
    notebook_name: str,
    run_cell: str,
) -> None:
    script = (ROOT / script_name).read_text(encoding="utf-8")
    cells: list[dict] = []

    for section in markdown_sections(summary_markdown.strip()):
        cells.append(markdown_cell(section))

    cells.append(
        markdown_cell(
            "# 配套实验代码\n\n"
            "下面按实验流程排列完整代码。首次运行保留 "
            "`RUN_QUICK = True`，确认流程正确后再运行正式实验。\n"
        )
    )
    for title, source in code_sections(script):
        translated_title = CODE_TITLE_TRANSLATIONS.get(title, title)
        cells.append(markdown_cell(f"## {translated_title}\n"))
        cells.append(code_cell(source))
    cells.append(markdown_cell("## 运行实验\n"))
    cells.append(code_cell(run_cell.strip() + "\n"))

    notebook = {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {"name": "python", "version": "3"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    (ROOT / notebook_name).write_text(
        json.dumps(notebook, ensure_ascii=False, indent=1) + "\n",
        encoding="utf-8",
    )


build_notebook(
    SECTION6_SUMMARY,
    "section6_conservation_pinn_burgers.py",
    "section6_conservation_pinn_burgers.ipynb",
    """
RUN_QUICK = True

cfg = Config()
if RUN_QUICK:
    cfg.epochs = 10
    cfg.n_ic = 32
    cfg.n_bc = 32
    cfg.n_f = 128
    cfg.n_cons_t = 8
    cfg.n_cons_x = 32
    cfg.hidden_dim = 32
    cfg.num_hidden = 3
    cfg.print_every = 1
    cfg.ref_nx = 128
    cfg.ref_dt = 1e-3
    cfg.output_dir = "results/section6_burgers_quick"

run_experiment(cfg)
""",
)

build_notebook(
    SECTION7_SUMMARY,
    "section7_double_pendulum_hamiltonian.py",
    "section7_double_pendulum_hamiltonian.ipynb",
    """
RUN_QUICK = True

if RUN_QUICK:
    run_experiment(t_end=1.0, dt=0.02, output_name="section7_double_pendulum_quick")
else:
    run_experiment(t_end=10.0, dt=0.005, output_name="section7_double_pendulum_dt_0p005")
""",
)
