"""Section 7 lab: solve a planar double pendulum in two canonical coordinates.

Run:
    python section7_double_pendulum_hamiltonian.py --quick
    python section7_double_pendulum_hamiltonian.py --t-end 10 --dt 0.005
"""

# %% Imports and physical parameters
from __future__ import annotations

import argparse
import csv
from dataclasses import dataclass
from pathlib import Path
from typing import Callable

import matplotlib.pyplot as plt
import numpy as np
import torch


@dataclass
class Parameters:
    m1: float = 1.0
    m2: float = 1.0
    l1: float = 1.0
    l2: float = 1.0
    g: float = 9.81


# %% Hamiltonian in the original canonical variables z = (q1, q2, p1, p2)
def hamiltonian(z: torch.Tensor, params: Parameters) -> torch.Tensor:
    q1, q2, p1, p2 = z.unbind(dim=-1)
    delta = q1 - q2
    denominator = (
        2.0
        * params.m2
        * params.l1**2
        * params.l2**2
        * (params.m1 + params.m2 * torch.sin(delta) ** 2)
    )
    numerator = (
        params.m2 * params.l2**2 * p1**2
        + (params.m1 + params.m2) * params.l1**2 * p2**2
        - 2.0
        * params.m2
        * params.l1
        * params.l2
        * torch.cos(delta)
        * p1
        * p2
    )
    potential = (
        -(params.m1 + params.m2) * params.g * params.l1 * torch.cos(q1)
        - params.m2 * params.g * params.l2 * torch.cos(q2)
    )
    return numerator / denominator + potential


def hamiltonian_rhs(
    state: np.ndarray,
    energy_function: Callable[[torch.Tensor, Parameters], torch.Tensor],
    params: Parameters,
) -> np.ndarray:
    """Return (d coordinates/dt, d momenta/dt) using automatic differentiation."""
    # Keep this calculation on CPU: MPS does not support float64, while the
    # small Hamiltonian drift measured in this lesson benefits from precision.
    z = torch.tensor(state, dtype=torch.float64, device="cpu", requires_grad=True)
    energy = energy_function(z, params)
    grad_h = torch.autograd.grad(energy, z)[0]
    dzdt = torch.cat((grad_h[2:], -grad_h[:2]))
    return dzdt.detach().numpy()


# %% A canonical transformation generated by F2(q,P)
def original_to_transformed(z: np.ndarray) -> np.ndarray:
    """Q1=q1, Q2=q2-q1, P1=p1+p2, P2=p2."""
    q1, q2, p1, p2 = np.moveaxis(np.asarray(z), -1, 0)
    return np.stack((q1, q2 - q1, p1 + p2, p2), axis=-1)


def transformed_to_original(z_new: np.ndarray) -> np.ndarray:
    """q1=Q1, q2=Q1+Q2, p1=P1-P2, p2=P2."""
    q1, q_relative, p_total, p2 = np.moveaxis(np.asarray(z_new), -1, 0)
    return np.stack((q1, q1 + q_relative, p_total - p2, p2), axis=-1)


def transformed_hamiltonian(z_new: torch.Tensor, params: Parameters) -> torch.Tensor:
    q1, q_relative, p_total, p2 = z_new.unbind(dim=-1)
    z_original = torch.stack((q1, q1 + q_relative, p_total - p2, p2), dim=-1)
    return hamiltonian(z_original, params)


def symplectic_defect() -> float:
    """Check A^T J A = J for z_original = A z_transformed."""
    identity = np.eye(2)
    zero = np.zeros((2, 2))
    symplectic_matrix = np.block([[zero, identity], [-identity, zero]])
    transform = np.array(
        [
            [1.0, 0.0, 0.0, 0.0],
            [1.0, 1.0, 0.0, 0.0],
            [0.0, 0.0, 1.0, -1.0],
            [0.0, 0.0, 0.0, 1.0],
        ]
    )
    return float(
        np.linalg.norm(transform.T @ symplectic_matrix @ transform - symplectic_matrix)
    )


# %% The same RK4 integrator is used for a fair coordinate comparison
def integrate_rk4(
    initial_state: np.ndarray,
    t_end: float,
    dt: float,
    energy_function: Callable[[torch.Tensor, Parameters], torch.Tensor],
    params: Parameters,
) -> tuple[np.ndarray, np.ndarray]:
    steps = int(np.ceil(t_end / dt))
    times = np.linspace(0.0, t_end, steps + 1)
    states = np.empty((steps + 1, len(initial_state)), dtype=np.float64)
    states[0] = initial_state

    for index in range(steps):
        step = times[index + 1] - times[index]
        state = states[index]
        k1 = hamiltonian_rhs(state, energy_function, params)
        k2 = hamiltonian_rhs(state + 0.5 * step * k1, energy_function, params)
        k3 = hamiltonian_rhs(state + 0.5 * step * k2, energy_function, params)
        k4 = hamiltonian_rhs(state + step * k3, energy_function, params)
        states[index + 1] = state + step * (k1 + 2 * k2 + 2 * k3 + k4) / 6.0
    return times, states


# %% Evaluation and plotting
def energy_history(states: np.ndarray, params: Parameters) -> np.ndarray:
    with torch.no_grad():
        tensor = torch.tensor(states, dtype=torch.float64, device="cpu")
        return hamiltonian(tensor, params).numpy()


def cartesian_positions(states: np.ndarray, params: Parameters) -> tuple[np.ndarray, ...]:
    q1, q2 = states[:, 0], states[:, 1]
    x1 = params.l1 * np.sin(q1)
    y1 = -params.l1 * np.cos(q1)
    x2 = x1 + params.l2 * np.sin(q2)
    y2 = y1 - params.l2 * np.cos(q2)
    return x1, y1, x2, y2


def plot_angles(
    times: np.ndarray, direct: np.ndarray, transformed: np.ndarray, output_dir: Path
) -> None:
    fig, axes = plt.subplots(2, 1, figsize=(9, 6), sharex=True)
    for index, axis in enumerate(axes):
        axis.plot(times, direct[:, index], label="Direct")
        axis.plot(times, transformed[:, index], "--", label="Canonical transform")
        axis.set_ylabel(f"q{index + 1} [rad]")
        axis.grid(alpha=0.3)
        axis.legend()
    axes[-1].set_xlabel("t [s]")
    fig.tight_layout()
    fig.savefig(output_dir / "01_angles.png", dpi=180)
    plt.close(fig)


def plot_tip_trajectory(
    direct: np.ndarray, transformed: np.ndarray, params: Parameters, output_dir: Path
) -> None:
    _, _, x2_direct, y2_direct = cartesian_positions(direct, params)
    _, _, x2_transformed, y2_transformed = cartesian_positions(transformed, params)
    fig, axis = plt.subplots(figsize=(6, 6))
    axis.plot(x2_direct, y2_direct, label="Direct")
    axis.plot(x2_transformed, y2_transformed, "--", label="Canonical transform")
    axis.set(xlabel="x2", ylabel="y2", title="Trajectory of the second mass")
    axis.axis("equal")
    axis.grid(alpha=0.3)
    axis.legend()
    fig.tight_layout()
    fig.savefig(output_dir / "02_tip_trajectory.png", dpi=180)
    plt.close(fig)


def plot_errors(
    times: np.ndarray,
    direct: np.ndarray,
    transformed: np.ndarray,
    params: Parameters,
    output_dir: Path,
) -> None:
    energy_direct = energy_history(direct, params)
    energy_transformed = energy_history(transformed, params)
    state_error = np.linalg.norm(direct - transformed, axis=1)

    fig, axes = plt.subplots(1, 2, figsize=(11, 4))
    axes[0].semilogy(times, np.abs(energy_direct - energy_direct[0]) + 1e-18, label="Direct")
    axes[0].semilogy(
        times,
        np.abs(energy_transformed - energy_transformed[0]) + 1e-18,
        "--",
        label="Canonical transform",
    )
    axes[0].set(xlabel="t [s]", ylabel="|H(t)-H(0)|", title="Hamiltonian drift")
    axes[0].legend()
    axes[1].semilogy(times, state_error + 1e-18)
    axes[1].set(xlabel="t [s]", ylabel="||z_direct-z_mapped||", title="Coordinate agreement")
    for axis in axes:
        axis.grid(alpha=0.3)
    fig.tight_layout()
    fig.savefig(output_dir / "03_energy_and_state_error.png", dpi=180)
    plt.close(fig)


def save_metrics(
    direct: np.ndarray,
    transformed: np.ndarray,
    params: Parameters,
    dt: float,
    output_dir: Path,
) -> None:
    energy_direct = energy_history(direct, params)
    energy_transformed = energy_history(transformed, params)
    rows = [
        {
            "dt": dt,
            "symplectic_defect": symplectic_defect(),
            "max_state_error": np.linalg.norm(direct - transformed, axis=1).max(),
            "max_energy_drift_direct": np.abs(energy_direct - energy_direct[0]).max(),
            "max_energy_drift_transformed": np.abs(
                energy_transformed - energy_transformed[0]
            ).max(),
        }
    ]
    with (output_dir / "metrics.csv").open("w", newline="", encoding="utf-8") as file:
        writer = csv.DictWriter(file, fieldnames=rows[0].keys())
        writer.writeheader()
        writer.writerows(rows)
    print({key: f"{value:.3e}" for key, value in rows[0].items()})


# %% Complete comparison experiment
def run_experiment(t_end: float, dt: float, output_name: str) -> None:
    params = Parameters()
    output_dir = Path(__file__).resolve().parent / "results" / output_name
    output_dir.mkdir(parents=True, exist_ok=True)

    # Zero initial angular velocities imply zero initial canonical momenta.
    original_initial = np.array([1.0, 0.2, 0.0, 0.0])
    transformed_initial = original_to_transformed(original_initial)

    print(f"symplectic defect: {symplectic_defect():.3e}")
    print("integrating original canonical variables...")
    times, direct_states = integrate_rk4(
        original_initial, t_end, dt, hamiltonian, params
    )
    print("integrating transformed canonical variables...")
    _, transformed_states = integrate_rk4(
        transformed_initial, t_end, dt, transformed_hamiltonian, params
    )
    mapped_states = transformed_to_original(transformed_states)

    plot_angles(times, direct_states, mapped_states, output_dir)
    plot_tip_trajectory(direct_states, mapped_states, params, output_dir)
    plot_errors(times, direct_states, mapped_states, params, output_dir)
    save_metrics(direct_states, mapped_states, params, dt, output_dir)
    np.savez(
        output_dir / "trajectories.npz",
        times=times,
        direct=direct_states,
        transformed=transformed_states,
        transformed_mapped=mapped_states,
    )
    print(f"results: {output_dir}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--t-end", type=float, default=10.0)
    parser.add_argument("--dt", type=float, default=0.005)
    parser.add_argument("--quick", action="store_true")
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    if args.quick:
        args.t_end = 1.0
        args.dt = 0.02
        output_name = "section7_double_pendulum_quick"
    else:
        dt_label = str(args.dt).replace(".", "p")
        output_name = f"section7_double_pendulum_dt_{dt_label}"
    run_experiment(args.t_end, args.dt, output_name)
